/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_v_zakudong_jniopencv_MainActivity */

#ifndef _Included_com_example_v_zakudong_jniopencv_MainActivity
#define _Included_com_example_v_zakudong_jniopencv_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_v_zakudong_jniopencv_MainActivity
 * Method:    ImgFun
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_v_1zakudong_jniopencv_MainActivity_ImgFun
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
